name: Windows RDP Access (ngrok)

on: [push, workflow_dispatch]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Set user password
      run: |
        net user runneradmin P@ssw0rd

    - name: Enable RDP
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 1 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive ngrok.zip -DestinationPath .
        Rename-Item ngrok.exe ngrokw.exe

    - name: Authenticate ngrok
      run: .\ngrokw.exe authtoken $env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose RDP via ngrok
      run: |
        Start-Process -NoNewWindow -FilePath .\ngrokw.exe -ArgumentList "tcp 3389 --log=stdout" -RedirectStandardOutput ngrok.log
        Start-Sleep -s 10

        $ngrokApi = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
        $publicUrl = $ngrokApi.tunnels[0].public_url
        $host = ($publicUrl -split '[:/]')[3]
        $port = ($publicUrl -split ':')[2]

        Write-Output "====================================="
        Write-Output "🚀 RDP Túnel Criado via ngrok (Windows)"
        Write-Output "Host: $host"
        Write-Output "Porta: $port"
        Write-Output "Usuário: runneradmin"
        Write-Output "Senha: P@ssw0rd"
        Write-Output ""
        Write-Output "➡️ Como conectar no Windows (cliente RDP):"
        Write-Output "   Endereço: $host:$port"
        Write-Output "   Usuário: runneradmin"
        Write-Output "   Senha: P@ssw0rd"
        Write-Output "====================================="

    - name: Keep session alive
      run: timeout 21600
