name: Ubuntu SSH Access (Cloudflared)

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq dnsutils
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo "runner:P@ssw0rd" | sudo chpasswd

    - name: Install cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

    - name: Expose SSH via Cloudflared
      run: |
        cloudflared tunnel --url tcp://localhost:22 --logfile cloudflared.log --no-autoupdate > cf.log 2>&1 &
        sleep 8
        echo "====================================="
        echo "🚀 SSH Túnel Criado via Cloudflared"
        cat cf.log | grep -Eo "tcp://[a-zA-Z0-9.-]+:[0-9]+"
        echo "Usuário: runner"
        echo "Senha: P@ssw0rd"
        echo "====================================="

    - name: Keep the job running
      run: sleep 6h
