name: macOS SSH Access (ngrok)

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: macos-latest

    steps:
    - name: Set up SSH Server
      run: |
        # Habilitar SSH no macOS runner
        sudo systemsetup -setremotelogin on
        # Definir senha para o usuário "runner"
        echo "runner:P@ssw0rd" | sudo chpasswd
        echo "✅ SSH server configurado no macOS"

    - name: Install dependencies
      run: |
        brew install wget jq

    - name: Install ngrok
      run: |
        wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.tgz
        tar xf ngrok-v3-stable-darwin-amd64.tgz
        chmod +x ./ngrok
        echo "✅ ngrok instalado"

    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose SSH via ngrok
      run: |
        ./ngrok tcp 22 --log=stdout > ngrok.log &
        sleep 8

        NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        NGROK_HOST=$(echo $NGROK_URL | sed -E 's#tcp://([^:]+):([0-9]+)#\1#')
        NGROK_PORT=$(echo $NGROK_URL | sed -E 's#tcp://([^:]+):([0-9]+)#\2#')

        echo "====================================="
        echo "🚀 SSH Túnel Criado via ngrok (macOS)"
        echo "Host: $NGROK_HOST"
        echo "Porta: $NGROK_PORT"
        echo "Usuário: runner"
        echo "Senha: P@ssw0rd"
        echo ""
        echo "Comando para conectar:"
        echo "ssh runner@$NGROK_HOST -p $NGROK_PORT"
        echo "====================================="

    - name: Keep the job running
      run: sleep 6h
